<a href="https://colab.research.google.com/github/AbdulWahabRaza123/NLP/blob/main/BERT(NLP_MODEL_Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [3]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)

In [5]:
text_test=['nice movie indeed','I love python programming']
text_preprocessed=bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [7]:
text_preprocessed['input_word_ids']
#word is storing in the form of CLS --- SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [8]:
#now importing model
bert_model=hub.KerasLayer(encoder_url)

In [9]:
bert_results=bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'default', 'pooled_output'])

In [11]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411902,  0.49769545, ...,  0.24465242,
        -0.47334465,  0.8175868 ],
       [-0.91712296, -0.47935185, -0.78656995, ..., -0.61751765,
        -0.71026856,  0.92184293]], dtype=float32)>

In [12]:
bert_results['default']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411902,  0.49769545, ...,  0.24465242,
        -0.47334465,  0.8175868 ],
       [-0.91712296, -0.47935185, -0.78656995, ..., -0.61751765,
        -0.71026856,  0.92184293]], dtype=float32)>

In [13]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292041,  0.08567816,  0.14476837, ..., -0.0967708 ,
          0.08722115,  0.07711103],
        [ 0.17839377, -0.19006082,  0.50349444, ..., -0.05869827,
          0.32717147, -0.15578502],
        [ 0.18701456, -0.4338877 , -0.48875162, ..., -0.1550281 ,
          0.00145131, -0.24470958],
        ...,
        [ 0.12083077,  0.12884237,  0.46453524, ...,  0.07375517,
          0.17441934,  0.16522089],
        [ 0.07967839, -0.01190699,  0.5022542 , ...,  0.13777757,
          0.21002182,  0.0062461 ],
        [-0.07212706, -0.2830349 ,  0.5903332 , ...,  0.47551912,
          0.1666846 , -0.08920319]],

       [[-0.07900587,  0.36335132, -0.2110159 , ..., -0.17183743,
          0.16299748,  0.6724267 ],
        [ 0.27883568,  0.43716288, -0.35764778, ..., -0.04463685,
          0.3831519 ,  0.588798  ],
        [ 1.2037668 ,  1.0727028 ,  0.48408768, ...,  0.24921045,
          0.40730873,  0.4048177 ],
        ...,

In [14]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901425,  0.0064474 , -0.03614967, ...,  0.04999621,
           0.06149199, -0.02657534],
         [ 1.1753383 ,  1.2140784 ,  1.1569982 , ...,  0.11634377,
          -0.3585536 , -0.40490198],
         [ 0.03859022,  0.53869987, -0.21089768, ...,  0.21858197,
           0.7260166 , -1.1158605 ],
         ...,
         [-0.07587015, -0.25421888,  0.7075511 , ...,  0.50542   ,
          -0.18878672,  0.1502834 ],
         [-0.16066599, -0.28089687,  0.57597077, ...,  0.5275854 ,
          -0.11141385,  0.02887553],
         [-0.04428148, -0.20279586,  0.59093565, ...,  0.81338364,
          -0.3907581 , -0.02601735]],
 
        [[ 0.18903589,  0.02752547, -0.06513736, ..., -0.00620209,
           0.15053898,  0.03165447],
         [ 0.591615  ,  0.758914  , -0.07240664, ...,  0.6190398 ,
           0.829289  ,  0.16161953],
         [ 1.4460828 ,  0.44602656,  0.40990266, ...,  0.48255897,
           0.6269114 ,  0.13