<a href="https://colab.research.google.com/github/AbdulWahabRaza123/NLP/blob/main/EmailClassificationNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

https://github.com/codebasics/nlp-tutorials/blob/main/9_bag_of_words/spam.csv

In [4]:
df=pd.read_csv('/content/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [9]:
#Now making a new colum with name as spam to show spam emails in 0 and 1 format
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
df.shape

(5572, 3)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [15]:
X_train.shape,X_test.shape

((4457,), (1115,))

In [16]:
type(X_train)

pandas.core.series.Series

In [18]:
X_train[:4]

4212                               Oi when you gonna ring
4516    That was random saw my old roomate on campus. ...
3232                   No plm i will come da. On the way.
2395    I don't run away frm u... I walk slowly &amp; ...
Name: Message, dtype: object

In [19]:
type(y_train)

pandas.core.series.Series

In [20]:
y_train[:4]

4212    0
4516    0
3232    0
2395    0
Name: spam, dtype: int64

In [22]:
type(X_train.values)

numpy.ndarray

In [32]:
#we can import count vectorization from sklearn
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7751 sparse matrix of type '<class 'numpy.int64'>'
	with 59206 stored elements in Compressed Sparse Row format>

In [34]:
#toarray() helping us to convert the class into array and I am showing first elements
X_train_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
X_train_cv.shape

(4457, 7751)

In [39]:
# These are the words vocabilary has 
v.get_feature_names_out()[1000:1050]

array(['anythiing', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'apeshit', 'apnt', 'apo', 'apologetic', 'apologise',
       'apologize', 'apology', 'app', 'apparently', 'appeal', 'appear',
       'appendix', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'appropriate', 'approve', 'approx',
       'apps', 'appt', 'appy', 'april', 'aproach', 'apt', 'aptitude',
       'aquarius', 'ar', 'arab', 'arabian', 'arcade'], dtype=object)

In [40]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [41]:
v.get_feature_names_out().shape

(7751,)

In [42]:
# to check all the methods
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [43]:
v.vocabulary_

{'oi': 4913,
 'when': 7482,
 'you': 7711,
 'gonna': 3193,
 'ring': 5791,
 'that': 6828,
 'was': 7396,
 'random': 5571,
 'saw': 5928,
 'my': 4684,
 'old': 4930,
 'roomate': 5822,
 'on': 4938,
 'campus': 1634,
 'he': 3380,
 'graduated': 3227,
 'no': 4804,
 'plm': 5263,
 'will': 7519,
 'come': 1915,
 'da': 2150,
 'the': 6832,
 'way': 7416,
 'don': 2412,
 'run': 5857,
 'away': 1175,
 'frm': 3019,
 'walk': 7368,
 'slowly': 6250,
 'amp': 949,
 'it': 3771,
 'kills': 3955,
 'me': 4427,
 'care': 1661,
 'enough': 2610,
 'to': 6950,
 'stop': 6506,
 'as': 1091,
 'valued': 7261,
 'customer': 2135,
 'am': 934,
 'pleased': 5258,
 'advise': 837,
 'following': 2935,
 'recent': 5633,
 'review': 5773,
 'of': 4893,
 'your': 7716,
 'mob': 4561,
 'are': 1052,
 'awarded': 1174,
 'with': 7549,
 '1500': 305,
 'bonus': 1433,
 'prize': 5425,
 'call': 1612,
 '09066364589': 229,
 'sorry': 6343,
 'll': 4176,
 'later': 4044,
 'oooh': 4955,
 'bed': 1295,
 'ridden': 5785,
 'ey': 2739,
 'what': 7475,
 'thinking': 6865,

In [45]:
# lets play a bit
X_train_np=X_train_cv.toarray()
# showing first email 
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [57]:
np.where(X_train_np[0]!=0)

(array([3193, 4913, 5791, 7482, 7711]),)

In [46]:
X_train[:4]

4212                               Oi when you gonna ring
4516    That was random saw my old roomate on campus. ...
3232                   No plm i will come da. On the way.
2395    I don't run away frm u... I walk slowly &amp; ...
Name: Message, dtype: object

In [62]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [63]:
X_train_np[0][3193]

1

In [64]:
v.get_feature_names_out()[3193]

'gonna'

In [65]:
#Importing model
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [66]:
X_test_cv=v.transform(X_test)

In [67]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.96      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [68]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

##More Easier Way of Doing This

In [69]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [70]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [71]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.96      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

