<a href="https://colab.research.google.com/github/AbdulWahabRaza123/NLP/blob/main/EmbadingUsingSuperviseNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing libraries
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
#reviews
reviews=[
    'nice food',
    'amazing restaraunt',
    'too good',
    'just loved it',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [24]:
#converting to one hot encoding (dummy)
one_hot("amazing restaraunt",30)

[29, 22]

In [7]:
#converting to on hot encoding
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[9, 20],
 [29, 22],
 [23, 24],
 [9, 3, 5],
 [28, 18, 6],
 [4, 20],
 [14, 18, 15],
 [20, 23],
 [20, 16],
 [7, 10]]

###Explain
After getting one hot encoding we will get the array here we will have different size of values here we will find the maz size of array and pad all the other arrays with 0

In [10]:
#applying padding here tensorflow has build in function for padding 
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding="post")
padded_reviews


array([[ 9, 20,  0],
       [29, 22,  0],
       [23, 24,  0],
       [ 9,  3,  5],
       [28, 18,  6],
       [ 4, 20,  0],
       [14, 18, 15],
       [20, 23,  0],
       [20, 16,  0],
       [ 7, 10,  0]], dtype=int32)

In [14]:
#embeded vector size
embedded_vector_size=4
#making model
model=Sequential()
#adding layers
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name="embedding"))
#second layer to make vectors flatten
model.add(Flatten())
#third layer applying sigmoid function
model.add(Dense(1,activation="sigmoid"))

In [15]:
X=padded_reviews
y=sentiment

In [17]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [18]:
#trainning
model.fit(X,y,epochs=50,verbose=0)

In [19]:
loss,accuracy=model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 137ms/step - loss: 0.6059 - accuracy: 0.9000


0.8999999761581421

In [20]:
#we can also see the weights of model embedding
model.get_layer('embedding').get_weights()[0]

array([[ 0.02014754,  0.01189462,  0.02402946, -0.07424595],
       [ 0.01773894, -0.00077007,  0.0168005 , -0.01721112],
       [ 0.01895732, -0.0059097 ,  0.02556277,  0.04224429],
       [-0.09252001, -0.01403051,  0.05330768,  0.08250262],
       [ 0.02580979,  0.04419846,  0.09915897, -0.03937206],
       [-0.04327674, -0.06454212, -0.0239429 ,  0.08799594],
       [-0.03906439, -0.00731874, -0.00692714,  0.08135056],
       [ 0.09218875,  0.07338219,  0.00905699, -0.05720693],
       [-0.03429835,  0.01012564, -0.04534793, -0.00710633],
       [-0.05407625, -0.07558817, -0.09292004,  0.07181469],
       [ 0.07677411,  0.00580222, -0.07905081, -0.05159359],
       [-0.04700832,  0.02355042,  0.03535397,  0.0096529 ],
       [ 0.00939365, -0.04302192,  0.00390413, -0.04935708],
       [-0.01071417, -0.02836871,  0.02362602,  0.00814857],
       [ 0.08562969,  0.08625933,  0.09484481, -0.10245387],
       [ 0.05359103,  0.010512  ,  0.09430351, -0.09391166],
       [ 0.09679034,  0.

In [22]:
#lets check the length
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [27]:
weights[9]#nice

array([-0.05407625, -0.07558817, -0.09292004,  0.07181469], dtype=float32)

In [30]:
weights[29]#amazing

array([-0.02089958, -0.07004186, -0.04180707,  0.05701059], dtype=float32)

In [31]:
#here both nice and amazing words has not much similar vector because our data set is very very small.